version: '3'

services:
  db:
    container_name: $MONGO_CONTAINER
    image: mongo:4.4.3
    networks:
      - db
    env_file:
      - .env
    environment:
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    restart: always
  app:
    image: node:14.16.1
    container_name: $CONTAINER_NAME
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    networks:
      - db
    env_file:
      - .env
    ports:
      - $APP_PORT:$APP_PORT
    depends_on:
      - db
    links:
      - db
    restart: always
    command: bash -c "chown -R node:node /usr/app && yarn && yarn $TYPE"
networks:
  db:
    driver: bridge
